//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public string CompID { get; set; }
        public string SiteID { get; set; }
        public string MyOrderID { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public Nullable<int> OrderLine { get; set; }
        public string LineType { get; set; }
        public string ProdID { get; set; }
        public Nullable<decimal> SellingQuantity { get; set; }
        public Nullable<double> UnitPrice { get; set; }
    
        public virtual ProductInSite ProductInSite { get; set; }
        public virtual Order Order { get; set; }
    }
}
