//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductInSites = new HashSet<ProductInSite>();
        }
    
        public string CompID { get; set; }
        public string PGroupID { get; set; }
        public string ProdID { get; set; }
        public string ProdName { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string UOM { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
    
        public virtual ProductGroup ProductGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductInSite> ProductInSites { get; set; }
    }
}
