//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoutePlan
    {
        public string CompID { get; set; }
        public string EmplID { get; set; }
        public int CustID { get; set; }
        public System.DateTime DatePlan { get; set; }
        public Nullable<int> Prioritize { get; set; }
        public Nullable<bool> Visited { get; set; }
        public string Note { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
