//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleTarget
    {
        public string CompID { get; set; }
        public int ID { get; set; }
        public string EmplID { get; set; }
        public Nullable<int> PeriodTarget { get; set; }
        public Nullable<int> YearTarget { get; set; }
        public Nullable<int> TargetQty { get; set; }
        public string Note { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
